kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-image
    image: plugins/docker:17.12
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO #ie. josmo/k8s-snapshots
      compress: false
      squash: true
      auto_tag: true
    when:
      ref:
        - refs/heads/master
        - refs/tags/*